### ISSUE TITLE
Failure with CMv2

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/docs#122]
I'm not able to complete the `CMv2` documentation due to errors.

This is what the docs show: https://docs.metaplex.com/candy-machine-v2/VerifyUpload

![image](https://user-images.githubusercontent.com/6530769/147420494-8dc82d61-f776-41a3-a9d5-42bcae003d18.png)

When running I got this failure:

```sh
$ ts-node ./js/packages/cli/src/candy-machine-v2-cli.ts mint_multiple_tokens --config-path config.json

error: unknown option '--config-path'
```

Why is `--config-path` in the docs but not actually working in the CLI?

I got the same issue with `verify` and `show`. Running on updated `master` branch.

**Comment by epomatti** [comment]
@stegaBOB

**Comment by bigsecret17** [comment]
i keep getting this error error: required option '-cp, --config-path <string>' not specified. this was the command i used npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair (PATH). PLEASEEE help me! i will give you one of my nft :)
