### ISSUE TITLE
Clarification on why "Once the sales begin, whitelist do not have any privileges"

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/docs#128]
In the [whitelist settings](https://docs.metaplex.com/candy-machine-v2/Configuration#whitelist-settings) page the first example says this:
> Once the sales begin, whitelist do not have any privileges

Is it correct? What does it mean?

```json
"whitelistMintSettings": {
    "mode" : { "burnEveryTime": true },
    "mint" : "7nE1GmnMmDKiycFkpHF7mKtxt356FQzVonZqBWsTWZNf",
    "presale" : true,
    "discountPrice" : null
}
```

**Comment by samuelvanderwaal** [comment]
Whitelist is for "presale", once that is over and the candy machine enters public sale it no longer checks for whitelist tokens when people call the mintFT handler.
