### ISSUE TITLE
./src/styles/index.less

### ISSUE THREAD

**Issue by RazHex** [metaplex-foundation/docs#181]
Hi there, After I've done all the steps from the documentation I'm getting this error when I'm compiling.

Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: src/pages/_app.tsx.
My machine is a MacBook Pro M1 Chip

Can anyone help me find a solution?Thank you.
<img width="1012" alt="Screenshot 2022-02-03 at 10 15 00" src="https://user-images.githubusercontent.com/16747754/152323186-f213c916-6b10-40a9-93ff-9095b523dc8e.png">

**Comment by stegaBOB** [comment]
If youre still having this issue, please open it up in the https://github.com/metaplex-foundation/metaplex repo
