### ISSUE TITLE
Creators deprecation poorly documented

### ISSUE THREAD

**Issue by zentale** [metaplex-foundation/docs#225]
Hi,
reading the complete documentation does not give you the answer what is replacing the creators array with the shares.
How should I create NFTs now, if I don't want to rely on a deprecated field?

https://github.com/metaplex-foundation/docs/blob/f47cee9b21b550a2769c4a83a7aa7f47636d79d6/docs/token-metadata/specification.md?plain=1#L214-L215

**Comment by lorisleiva** [comment]
Hi there, sorry for the late reply. Closing this as the Token Metadata documentation has been rewritten from scratch since then.
