### ISSUE TITLE
AWS Upload candy machine 

### ISSUE THREAD

**Issue by stegaBOB** [metaplex-foundation/docs#230]
Finally able to fix this.

In the uploadFile function this log should be changed to info so that you can get the error:

```
 try {
    await s3Client.send(new PutObjectCommand(mediaUploadParams));
  } catch (err) {
    log.debug('Error', err);
  }
```

The problem was that ACL has to be enabled. This not noted anywhere in the documentation.

I would recommend adding this to documentation + changing the `log.debug` to `log.info` in the catch.

_Originally posted by @MoMannn in https://github.com/metaplex-foundation/metaplex/issues/1849#issuecomment-1064133793_

**Comment by HectorNBL** [comment]
I added a reminder at the end of the AWS section where I mentioned what @MoMannn used as a fix in case other users haven't enabled ACL in their buckets.

**Comment by lorisleiva** [comment]
Closing this as it seems it's been tackled.
