### ISSUE TITLE
Auction House CLI docs referring to deprecated CLI, when there is a slightly more updated version

### ISSUE THREAD

**Issue by aa21** [metaplex-foundation/docs#404]
**Why is the Auction House CLI docs referring to deprecated CLI, when there is a slightly more updated version?**

Docs:
https://docs.metaplex.com/programs/auction-house/how-to-guides/manage-auction-house-using-cli

Latest Auction House CLI:
https://github.com/metaplex-foundation/metaplex-program-library/blob/master/auction-house/cli/src/auction-house-cli.ts

Deprecated Auction House CLI:
https://github.com/metaplex-foundation/deprecated-clis/blob/main/src/auction-house-cli.ts

Not hating - I really appreciate the amazing work put in but Metaplex developers .. BUT someone has to be the noisy bird, so here goes:

Overall, Metaplex code is very badly organised and managed on Github. Rust and JS code are lumped together. Documentation is all over the place - some on github, some on docs.metaplex.com, missing critical information like breaking/compatible versions, some info on metaplex-foundation.github.io etc

I hope you guys will take a look into this bad organisation and clean it up. There was obviously an enthusiastic effort to develop many projects - but the support for clean code organisation, developer experience when setting up, documentation etc is poor.

**Comment by MarkSackerberg** [comment]
Hi @aa21 
thanks for flagging this! I've created #416 to reflect your proposal.

I'll also forward the last two paragraphs :)

**Comment by aa21** [comment]
Thank you @MarkSackerberg for your contribution :)
