### ISSUE TITLE
Collections inconsistently referenced

### ISSUE THREAD

**Issue by pistachiomatt** [metaplex-foundation/docs#55]
Hey team! Thanks so much for the tremendous work in this space.

I've seen inconsistent references to a `collection` key for the `Metadata` token in the docs. (However, the metaplex app and @metaplex/js do not reference collections from what I've seen.) Can NFTs live inside collections? Is that part of the standard?

**Comment by aheckmann** [comment]
Here's what the standard says about collections today

https://docs.metaplex.com/nft-standard#collections
